version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/python
    working_directory: ~/code
    steps:
      - checkout
      - save_cache:
          key: code-{{ .Revision }}
          paths:
            - ~/code

  build_image:
    docker:
      - image: circleci/python
    working_directory: ~/code
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - restore_cache:
          keys:
            - code-{{ .Revision }}
      - restore_cache:
          keys:
            - build-client-{{ .Revision }}
      - restore_cache:
          keys:
            - docker-images-{{ .Branch }}
      - run:
          name: Build docker image
          command: |
            set +o pipefail
            if [ -f ~/docker-images.tar.gz ]; then
              gunzip -c ~/docker-images.tar.gz | docker load
              docker build --cache-from=pugdit:$CIRCLE_BRANCH --tag pugdit:$CIRCLE_SHA1 --tag pugdit:$CIRCLE_BRANCH .
            else
              docker build --tag pugdit:$CIRCLE_SHA1 --tag pugdit:$CIRCLE_BRANCH .
            fi
      - run:
          name: Save Docker image layer cache
          command: docker save pugdit:$CIRCLE_SHA1 | gzip > ~/docker-images.tar.gz
      - save_cache:
          key: docker-images-{{ .Branch }}
          paths:
            - ~/docker-images.tar.gz
      - save_cache:
          key: docker-images-{{ .Revision }}
          paths:
            - ~/docker-images.tar.gz

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build_image:
          requires:
            - checkout_code
